module.exports = {
  frCentralId: 'fr_central_id',
  plotRegistryId: 'plot_registry_id',
  farmerLandOwnershipRegistryId: 'farmer_land_ownership_registry_id',
  farmlandId: 'farmland_id',
  surveyNumber: 'survey_number',
  subSurveyNumber: 'sub_survey_number',
  plotStateLgdCode: 'plot_state_lgd_code',
  plotStateName: 'plot_state_name',
  plotVillageLgdCode: 'plot_village_lgd_code',
  plotVillageName: 'plot_village_name',
  plotDistrictLgdCode: 'plot_district_lgd_code',
  plotDistrictName: 'plot_district_name',
  plotSubDistrictLgdCode: 'plot_sub_district_lgd_code',
  plotSubDistrictName: 'plot_sub_district_name',
  mainOwnerNoAsPerRor: 'main_owner_no_as_per_ror',
  ownerNoAsPerRor: 'owner_no_as_per_ror',
  ownerNamePerRor: 'owner_name_per_ror',
  ownerIdentifierNamePerRor: 'owner_identifier_name_per_ror',
  extentAssignAreaInHectare: 'extent_assign_area_in_hectare',
  extentTotalAreaInHectare: 'extent_total_area_in_hectare',
  isJointOwnership: 'is_joint_ownership',
  ownerType: 'ownerType',
  ownershipShareType: 'ownershipShareType',
  jointOwnershipShareType: 'jointOwnershipShareType',
};
