// camelCase (GraphQL / config attribute name) -> snake_case (ClickHouse column)
module.exports = {
  frCentralId: 'fr_central_id',
  farmerNameEng: 'farmer_name_eng',
  farmerNameLocal: 'farmer_name_local',
  identifierNameEng: 'identifier_name_eng',
  identifierNameLocal: 'identifier_name_local',
  farmerIdentifierRelationship: 'farmer_identifier_relationship',
  farmerMobileNumber: 'farmer_mobile_number',
  farmerAddressEnglish: 'farmer_address_english',
  farmerAddressLocal: 'farmer_address_local',
  farmerAadhaarHash: 'farmer_aadhaar_hash',
  farmerAadhaarBase64Hash: 'farmer_aadhaar_base64_hash',
  farmerAadhaarMask: 'farmer_aadhaar_mask',
  farmerDob: 'farmer_dob',
  gender: 'gender',
  farmerPan: 'farmer_pan',
  farmerCategory: 'farmer_category',
  farmerCasteCategory: 'farmer_caste_category',
  frStateLgdCode: 'fr_state_lgd_code',
  frStateName: 'fr_state_name',
  frVillageLgdCode: 'fr_village_lgd_code',
  frVillageName: 'fr_village_name',
  frDistrictLgdCode: 'fr_district_lgd_code',
  frDistrictName: 'fr_district_name',
  frSubDistrictLgdCode: 'fr_sub_district_lgd_code',
  frSubDistrictName: 'fr_sub_district_name',
  pmKisanId: 'pm_kisan_id',
  farmerType: 'farmerType',
};
